<?php

declare(strict_types=1);

if (class_exists('\Isolated\Symfony\Component\Finder\Finder')) {
	class_alias(
		\Isolated\Symfony\Component\Finder\Finder::class,
		'SymfonyFinder'
	);
} elseif (class_exists('Symfony\Component\Finder\Finder')) {
	class_alias(
		\Symfony\Component\Finder\Finder::class,
		'SymfonyFinder'
	);
} else {
	throw new \RuntimeException('Symfony Finder is not available.');
}

$getExcludes = require __DIR__ . '/vendor/wptechnix/php-scoper-wordpress-excludes/scoper.inc.php';

$wpExcludes = $getExcludes();

$excludeClasses = array_merge(
	$wpExcludes['exclude-classes'],
	[
		'/^$/',
	]
);

$excludeFunctions = array_merge(
	$wpExcludes['exclude-functions'],
	[
		'/^$/',
	]
);

$excludeConstants = array_merge(
	$wpExcludes['exclude-constants'],
	[
		'/^$/',
	]
);

return [
	// The prefix configuration. If a non-null value is used, a random prefix
	// will be generated instead.
	//
	// For more see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#prefix
	'prefix' => 'WPPluginBoilerplate_Deps',

	// Scope ONLY the plugin's installed runtime dependencies (plugin/vendor), never the
	// plugin's own source in plugin/src. That keeps the public `WPPluginBoilerplate\`
	// namespace intact for WordPress hooks and other plugins to reference.
	//
	// php-scoper strips the longest common base path shared by every scanned file and
	// appends the remainder to --output-dir. Scanning a single root (plugin/vendor)
	// makes that base plugin/vendor, so files land directly under vendor-prefixed/
	// (not nested under vendor-prefixed/vendor/). Do NOT add plugin/composer.json to
	// the finders. It would raise the common base to plugin/ and nest the whole output
	// one level deeper. The scoped autoloader is regenerated by
	// `composer dump-autoload` in scripts/scope.
	//
	// For more see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#finders-and-paths
	'finders' => is_dir(__DIR__ . '/plugin/vendor')
		? [
			SymfonyFinder::create()
				->files()
				->in('plugin/vendor'),
		]
		: [],

	// List of excluded files, i.e. files for which the content will be left
	// untouched. Paths are relative to the configuration file unless already
	// absolute.
	//
	// For more see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#patchers
	'exclude-files' => [],

	// When scoping PHP files, there will be scenarios where some of the code
	// being scoped indirectly references the original namespace. These include,
	// for example, strings or string manipulations. PHP-Scoper has limited
	// support for prefixing such strings. To work around that, define patchers
	// to manipulate the file as needed.
	//
	// For more see: https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#patchers
	'patchers' => [],

	// List of symbols to consider internal, i.e. to leave untouched.
	//
	// For more information see:
	// https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#excluded-symbols
	'exclude-namespaces' => [
		'WPPluginBoilerplate',
	],
	'exclude-classes' => $excludeClasses,
	'exclude-functions' => $excludeFunctions,
	'exclude-constants' => $excludeConstants,

	// List of symbols to expose.
	//
	// For more information see:
	// https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#exposed-symbols
	'expose-global-constants' => false,
	'expose-global-classes' => false,
	'expose-global-functions' => false,
	'expose-namespaces' => [
		// 'Acme\Foo'                  // The Acme\Foo namespace (and sub-namespaces)
		// '~^PHPUnit\\\\Framework$~', // The PHPUnit\Framework namespace only.
		// '~^$~',                     // The root namespace only.
		// '',                         // Any namespace.
	],
	'expose-classes' => [],
	'expose-functions' => [],
	'expose-constants' => [],
];
